#include<iostream>
#include<chrono>
#include<thread>
#include<filesystem>
#include<linuxsampler/Sampler.h>
#include<linuxsampler/drivers/audio/AudioOutputDeviceFactory.h>

namespace fs = std::__fs::filesystem;

int main() {
    auto sampler = new LinuxSampler::Sampler();
    auto factory = new LinuxSampler::AudioOutputDeviceFactory();

    auto params = std::map<std::string, std::string>();
    params["BUFFERSIZE"] = "2048";
    params["BUFFERS"] = "4";
    auto device = factory->Create("COREAUDIO", params);
auto trombone = sampler->AddSamplerChannel();
trombone->SetAudioOutputDevice(device);
trombone->SetEngineType("SFZ");
trombone->GetEngineChannel()->PrepareLoadInstrument(
(fs::current_path() / ".." / ".." / "resources" / "sfz" / "Jeux14" / "000/025_Trompette_8.sfz").string().c_str(),
  0);
trombone->GetEngineChannel()->LoadInstrument();

auto bassoon = sampler->AddSamplerChannel();
bassoon->SetAudioOutputDevice(device);
bassoon->SetEngineType("SFZ");
bassoon->GetEngineChannel()->PrepareLoadInstrument(
(fs::current_path() / ".." / ".." / "resources" / "sfz" / "Jeux14" / "001/055_Voix_Celeste_8.sfz").string().c_str(),
  0);
bassoon->GetEngineChannel()->LoadInstrument();

auto trumpet = sampler->AddSamplerChannel();
trumpet->SetAudioOutputDevice(device);
trumpet->SetEngineType("SFZ");
trumpet->GetEngineChannel()->PrepareLoadInstrument(
(fs::current_path() / ".." / ".." / "resources" / "sfz" / "Jeux14" / "000/069_Quintadena8Viola4.sfz").string().c_str(),
  0);
trumpet->GetEngineChannel()->LoadInstrument();

auto timpani = sampler->AddSamplerChannel();
timpani->SetAudioOutputDevice(device);
timpani->SetEngineType("SFZ");
timpani->GetEngineChannel()->PrepareLoadInstrument(
(fs::current_path() / ".." / ".." / "resources" / "sfz" / "Jeux14" / "000/073_Cornemuse_8.sfz").string().c_str(),
  0);
timpani->GetEngineChannel()->LoadInstrument();

auto strings = sampler->AddSamplerChannel();
strings->SetAudioOutputDevice(device);
strings->SetEngineType("SFZ");
strings->GetEngineChannel()->PrepareLoadInstrument(
(fs::current_path() / ".." / ".." / "resources" / "sfz" / "Jeux14" / "000/065_Quintadena_8.sfz").string().c_str(),
  0);
strings->GetEngineChannel()->LoadInstrument();

auto voice = sampler->AddSamplerChannel();
voice->SetAudioOutputDevice(device);
voice->SetEngineType("SFZ");
voice->GetEngineChannel()->PrepareLoadInstrument(
(fs::current_path() / ".." / ".." / "resources" / "sfz" / "Jeux14" / "000/000_Montre_8.sfz").string().c_str(),
  0);
voice->GetEngineChannel()->LoadInstrument();

trumpet->GetEngineChannel()->SendNoteOn(58, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(46, 80, 0);
strings->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(58, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOn(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(58, 80, 0);
trumpet->GetEngineChannel()->SendNoteOff(58, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(46, 80, 0);
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(58, 80, 0);
strings->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(58, 80, 0);
voice->GetEngineChannel()->SendNoteOn(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(53, 80, 0);
strings->GetEngineChannel()->SendNoteOff(58, 80, 0);
strings->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(53, 80, 0);
voice->GetEngineChannel()->SendNoteOn(61, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(61, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(61, 80, 0);
trumpet->GetEngineChannel()->SendNoteOn(58, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(46, 80, 0);
strings->GetEngineChannel()->SendNoteOff(58, 80, 0);
strings->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(58, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(61, 80, 0);
voice->GetEngineChannel()->SendNoteOn(58, 80, 0);
voice->GetEngineChannel()->SendNoteOn(61, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(61, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(61, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(61, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(61, 80, 0);
trumpet->GetEngineChannel()->SendNoteOff(58, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(46, 80, 0);
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(58, 80, 0);
strings->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(61, 80, 0);
voice->GetEngineChannel()->SendNoteOn(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(61, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(61, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(58, 80, 0);
strings->GetEngineChannel()->SendNoteOff(58, 80, 0);
strings->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(58, 80, 0);
voice->GetEngineChannel()->SendNoteOff(58, 80, 0);
voice->GetEngineChannel()->SendNoteOn(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(63, 80, 0);
trumpet->GetEngineChannel()->SendNoteOn(63, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(51, 80, 0);
strings->GetEngineChannel()->SendNoteOff(58, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOn(60, 80, 0);
voice->GetEngineChannel()->SendNoteOff(63, 80, 0);
voice->GetEngineChannel()->SendNoteOn(57, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(60, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(60, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(57, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(57, 80, 0);
trumpet->GetEngineChannel()->SendNoteOff(63, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(51, 80, 0);
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(60, 80, 0);
voice->GetEngineChannel()->SendNoteOn(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(60, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(60, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(53, 80, 0);
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(53, 80, 0);
voice->GetEngineChannel()->SendNoteOn(63, 80, 0);
voice->GetEngineChannel()->SendNoteOff(57, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(57, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(57, 80, 0);
trumpet->GetEngineChannel()->SendNoteOn(63, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(51, 80, 0);
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(63, 80, 0);
voice->GetEngineChannel()->SendNoteOn(57, 80, 0);
voice->GetEngineChannel()->SendNoteOn(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(57, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(57, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(63, 80, 0);
trumpet->GetEngineChannel()->SendNoteOff(63, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(51, 80, 0);
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(63, 80, 0);
voice->GetEngineChannel()->SendNoteOn(60, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(60, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(60, 80, 0);
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(57, 80, 0);
voice->GetEngineChannel()->SendNoteOff(60, 80, 0);
voice->GetEngineChannel()->SendNoteOn(65, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(57, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(57, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(60, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(65, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(60, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(65, 80, 0);
trumpet->GetEngineChannel()->SendNoteOn(58, 80, 0);
trumpet->GetEngineChannel()->SendNoteOn(65, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(46, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(53, 80, 0);
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(65, 80, 0);
voice->GetEngineChannel()->SendNoteOn(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(65, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(65, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(58, 80, 0);
voice->GetEngineChannel()->SendNoteOn(65, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(65, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(65, 80, 0);
trumpet->GetEngineChannel()->SendNoteOff(58, 80, 0);
trumpet->GetEngineChannel()->SendNoteOff(65, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(46, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(53, 80, 0);
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(65, 80, 0);
voice->GetEngineChannel()->SendNoteOn(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(65, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(65, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(63, 80, 0);
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(58, 80, 0);
voice->GetEngineChannel()->SendNoteOff(63, 80, 0);
voice->GetEngineChannel()->SendNoteOn(61, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(61, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(61, 80, 0);
trumpet->GetEngineChannel()->SendNoteOn(58, 80, 0);
trumpet->GetEngineChannel()->SendNoteOn(65, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(46, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(53, 80, 0);
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(61, 80, 0);
voice->GetEngineChannel()->SendNoteOn(60, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(61, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(60, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(61, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(60, 80, 0);
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(60, 80, 0);
voice->GetEngineChannel()->SendNoteOn(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(60, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(60, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(58, 80, 0);
trumpet->GetEngineChannel()->SendNoteOff(58, 80, 0);
trumpet->GetEngineChannel()->SendNoteOff(65, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(46, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(53, 80, 0);
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(58, 80, 0);
voice->GetEngineChannel()->SendNoteOn(56, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(56, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(56, 80, 0);
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(56, 80, 0);
voice->GetEngineChannel()->SendNoteOn(54, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(56, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(54, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(56, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(54, 80, 0);
trumpet->GetEngineChannel()->SendNoteOn(63, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(51, 80, 0);
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(66, 80, 0);
strings->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(66, 80, 0);
strings->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOn(66, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(66, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(66, 80, 0);
voice->GetEngineChannel()->SendNoteOff(54, 80, 0);
voice->GetEngineChannel()->SendNoteOn(51, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(54, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(51, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(54, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(51, 80, 0);
trumpet->GetEngineChannel()->SendNoteOff(63, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(51, 80, 0);
strings->GetEngineChannel()->SendNoteOff(66, 80, 0);
strings->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(66, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(66, 80, 0);
voice->GetEngineChannel()->SendNoteOn(65, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(66, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(65, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(66, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(65, 80, 0);
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(65, 80, 0);
voice->GetEngineChannel()->SendNoteOn(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(65, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(65, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(63, 80, 0);
voice->GetEngineChannel()->SendNoteOff(51, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(51, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(51, 80, 0);
trumpet->GetEngineChannel()->SendNoteOn(63, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(51, 80, 0);
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(66, 80, 0);
strings->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(63, 80, 0);
voice->GetEngineChannel()->SendNoteOn(61, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(61, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(61, 80, 0);
strings->GetEngineChannel()->SendNoteOff(66, 80, 0);
strings->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(0));
voice->GetEngineChannel()->SendNoteOff(61, 80, 0);
voice->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(0));
bassoon->GetEngineChannel()->SendNoteOn(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(0));
bassoon->GetEngineChannel()->SendNoteOff(61, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(60, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(61, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(0));
trumpet->GetEngineChannel()->SendNoteOff(63, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(51, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(0));
strings->GetEngineChannel()->SendNoteOff(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(0));
strings->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(66, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(63, 80, 0);
voice->GetEngineChannel()->SendNoteOn(63, 80, 0);
voice->GetEngineChannel()->SendNoteOff(60, 80, 0);
voice->GetEngineChannel()->SendNoteOn(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(60, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(60, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(58, 80, 0);
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(63, 80, 0);
voice->GetEngineChannel()->SendNoteOn(63, 80, 0);
voice->GetEngineChannel()->SendNoteOff(58, 80, 0);
voice->GetEngineChannel()->SendNoteOn(57, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(57, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(57, 80, 0);
trumpet->GetEngineChannel()->SendNoteOn(65, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(53, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(68, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(63, 80, 0);
voice->GetEngineChannel()->SendNoteOn(53, 80, 0);
voice->GetEngineChannel()->SendNoteOff(57, 80, 0);
voice->GetEngineChannel()->SendNoteOn(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(57, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(57, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(53, 80, 0);
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(53, 80, 0);
voice->GetEngineChannel()->SendNoteOff(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(53, 80, 0);
voice->GetEngineChannel()->SendNoteOn(57, 80, 0);
voice->GetEngineChannel()->SendNoteOn(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(57, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(57, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(63, 80, 0);
trumpet->GetEngineChannel()->SendNoteOff(65, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(53, 80, 0);
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(60, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(60, 80, 0);
strings->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(68, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(57, 80, 0);
voice->GetEngineChannel()->SendNoteOn(53, 80, 0);
voice->GetEngineChannel()->SendNoteOff(63, 80, 0);
voice->GetEngineChannel()->SendNoteOn(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(57, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(57, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(63, 80, 0);
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(53, 80, 0);
voice->GetEngineChannel()->SendNoteOn(61, 80, 0);
voice->GetEngineChannel()->SendNoteOff(63, 80, 0);
voice->GetEngineChannel()->SendNoteOn(64, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(61, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(61, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(63, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(64, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(63, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(64, 80, 0);
trumpet->GetEngineChannel()->SendNoteOn(58, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(46, 80, 0);
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(58, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(61, 80, 0);
voice->GetEngineChannel()->SendNoteOn(58, 80, 0);
voice->GetEngineChannel()->SendNoteOff(64, 80, 0);
voice->GetEngineChannel()->SendNoteOn(64, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(61, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(61, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(64, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(64, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(64, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(64, 80, 0);
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(58, 80, 0);
voice->GetEngineChannel()->SendNoteOn(61, 80, 0);
voice->GetEngineChannel()->SendNoteOff(64, 80, 0);
voice->GetEngineChannel()->SendNoteOn(64, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(61, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(61, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(64, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(64, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(64, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(64, 80, 0);
trumpet->GetEngineChannel()->SendNoteOff(58, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(46, 80, 0);
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(87));
strings->GetEngineChannel()->SendNoteOff(58, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(61, 80, 0);
voice->GetEngineChannel()->SendNoteOn(58, 80, 0);
voice->GetEngineChannel()->SendNoteOff(64, 80, 0);
voice->GetEngineChannel()->SendNoteOn(64, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(61, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(61, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(64, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(64, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(64, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(64, 80, 0);
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(58, 80, 0);
voice->GetEngineChannel()->SendNoteOn(57, 80, 0);
voice->GetEngineChannel()->SendNoteOff(64, 80, 0);
voice->GetEngineChannel()->SendNoteOn(65, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(58, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(57, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(58, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(57, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(64, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(65, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(64, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(65, 80, 0);
trumpet->GetEngineChannel()->SendNoteOn(65, 80, 0);
timpani->GetEngineChannel()->SendNoteOn(53, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOff(57, 80, 0);
voice->GetEngineChannel()->SendNoteOn(53, 80, 0);
voice->GetEngineChannel()->SendNoteOff(65, 80, 0);
voice->GetEngineChannel()->SendNoteOn(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(57, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(57, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(65, 80, 0);
bassoon->GetEngineChannel()->SendNoteOn(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(65, 80, 0);
trombone->GetEngineChannel()->SendNoteOn(53, 80, 0);
trumpet->GetEngineChannel()->SendNoteOff(65, 80, 0);
timpani->GetEngineChannel()->SendNoteOff(53, 80, 0);
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(698));
voice->GetEngineChannel()->SendNoteOff(53, 80, 0);
voice->GetEngineChannel()->SendNoteOff(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(53, 80, 0);
bassoon->GetEngineChannel()->SendNoteOff(53, 80, 0);
trombone->GetEngineChannel()->SendNoteOff(53, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(1395));
voice->GetEngineChannel()->SendNoteOn(73, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
voice->GetEngineChannel()->SendNoteOn(77, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(68, 80, 0);
strings->GetEngineChannel()->SendNoteOn(73, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOff(73, 80, 0);
strings->GetEngineChannel()->SendNoteOn(72, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOff(72, 80, 0);
strings->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOff(70, 80, 0);
strings->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOff(68, 80, 0);
strings->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOff(73, 80, 0);
voice->GetEngineChannel()->SendNoteOn(73, 80, 0);
strings->GetEngineChannel()->SendNoteOff(66, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
voice->GetEngineChannel()->SendNoteOff(77, 80, 0);
voice->GetEngineChannel()->SendNoteOn(77, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOn(73, 80, 0);
voice->GetEngineChannel()->SendNoteOff(73, 80, 0);
voice->GetEngineChannel()->SendNoteOn(75, 80, 0);
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
voice->GetEngineChannel()->SendNoteOff(77, 80, 0);
voice->GetEngineChannel()->SendNoteOn(78, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(73, 80, 0);
voice->GetEngineChannel()->SendNoteOn(72, 80, 0);
strings->GetEngineChannel()->SendNoteOff(66, 80, 0);
strings->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOff(75, 80, 0);
voice->GetEngineChannel()->SendNoteOn(75, 80, 0);
strings->GetEngineChannel()->SendNoteOff(68, 80, 0);
strings->GetEngineChannel()->SendNoteOn(56, 80, 0);
voice->GetEngineChannel()->SendNoteOff(78, 80, 0);
voice->GetEngineChannel()->SendNoteOn(78, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOff(72, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(0));
voice->GetEngineChannel()->SendNoteOff(75, 80, 0);
voice->GetEngineChannel()->SendNoteOn(73, 80, 0);
strings->GetEngineChannel()->SendNoteOff(56, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
voice->GetEngineChannel()->SendNoteOff(78, 80, 0);
voice->GetEngineChannel()->SendNoteOn(77, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(68, 80, 0);
strings->GetEngineChannel()->SendNoteOn(73, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOff(73, 80, 0);
strings->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(68, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(73, 80, 0);
voice->GetEngineChannel()->SendNoteOn(73, 80, 0);
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
voice->GetEngineChannel()->SendNoteOff(77, 80, 0);
voice->GetEngineChannel()->SendNoteOn(77, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(68, 80, 0);
strings->GetEngineChannel()->SendNoteOn(73, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOff(73, 80, 0);
voice->GetEngineChannel()->SendNoteOn(73, 80, 0);
strings->GetEngineChannel()->SendNoteOff(73, 80, 0);
strings->GetEngineChannel()->SendNoteOn(72, 80, 0);
voice->GetEngineChannel()->SendNoteOff(77, 80, 0);
voice->GetEngineChannel()->SendNoteOn(77, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOff(73, 80, 0);
voice->GetEngineChannel()->SendNoteOn(73, 80, 0);
strings->GetEngineChannel()->SendNoteOff(72, 80, 0);
strings->GetEngineChannel()->SendNoteOn(70, 80, 0);
voice->GetEngineChannel()->SendNoteOff(77, 80, 0);
voice->GetEngineChannel()->SendNoteOn(77, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOff(73, 80, 0);
voice->GetEngineChannel()->SendNoteOn(73, 80, 0);
strings->GetEngineChannel()->SendNoteOff(70, 80, 0);
strings->GetEngineChannel()->SendNoteOn(68, 80, 0);
voice->GetEngineChannel()->SendNoteOff(77, 80, 0);
voice->GetEngineChannel()->SendNoteOn(77, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOff(73, 80, 0);
voice->GetEngineChannel()->SendNoteOn(73, 80, 0);
strings->GetEngineChannel()->SendNoteOff(68, 80, 0);
strings->GetEngineChannel()->SendNoteOn(66, 80, 0);
voice->GetEngineChannel()->SendNoteOff(77, 80, 0);
voice->GetEngineChannel()->SendNoteOn(77, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOff(73, 80, 0);
voice->GetEngineChannel()->SendNoteOn(73, 80, 0);
strings->GetEngineChannel()->SendNoteOff(66, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
voice->GetEngineChannel()->SendNoteOff(77, 80, 0);
voice->GetEngineChannel()->SendNoteOn(77, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOn(73, 80, 0);
voice->GetEngineChannel()->SendNoteOff(73, 80, 0);
voice->GetEngineChannel()->SendNoteOn(75, 80, 0);
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(63, 80, 0);
voice->GetEngineChannel()->SendNoteOff(77, 80, 0);
voice->GetEngineChannel()->SendNoteOn(78, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOff(63, 80, 0);
strings->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
strings->GetEngineChannel()->SendNoteOff(65, 80, 0);
strings->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(174));
voice->GetEngineChannel()->SendNoteOff(73, 80, 0);
voice->GetEngineChannel()->SendNoteOn(72, 80, 0);
strings->GetEngineChannel()->SendNoteOff(66, 80, 0);
strings->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOff(68, 80, 0);
strings->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOff(72, 80, 0);
voice->GetEngineChannel()->SendNoteOff(75, 80, 0);
voice->GetEngineChannel()->SendNoteOn(73, 80, 0);
strings->GetEngineChannel()->SendNoteOff(56, 80, 0);
strings->GetEngineChannel()->SendNoteOn(61, 80, 0);
voice->GetEngineChannel()->SendNoteOff(78, 80, 0);
voice->GetEngineChannel()->SendNoteOn(77, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
strings->GetEngineChannel()->SendNoteOff(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(349));
voice->GetEngineChannel()->SendNoteOff(73, 80, 0);
voice->GetEngineChannel()->SendNoteOff(77, 80, 0);
}
